PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX yago: <http://dbpedia.org/class/yago/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT ?pref ?area
WHERE {
  ?s a yago:WikicatPrefecturesOfJapan ;
     rdfs:label ?pref ;
     dbpedia-owl:areaTotal ?area .
  FILTER (lang(?pref) = 'en')
  ## a bug of YAGO in DBpedia 2016-04 ?
  FILTER (str(?pref) != 'Onjuku') 
}
ORDER BY DESC(?area)
