PREFIX dbpedia-ja: <http://ja.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?film_name ?director_beat ?director_kitano
{
 {
  ?film dbpedia-owl:director ?director_beat .
  FILTER(?director_beat = dbpedia-ja:ビートたけし) . 
 }
 UNION
 {
  ?film dbpedia-owl:director ?director_kitano .
  FILTER(?director_kitano = dbpedia-ja:北野武) . 
 }
 ?film rdfs:label ?film_name .
}