PREFIX dbpedia-ja: <http://ja.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX prop-ja: <http://ja.dbpedia.org/property/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?film_name ?screen_time
{
  ?film dbpedia-owl:director ?director ;
    rdfs:label ?film_name ;
    prop-ja:上映時間 ?screen_time .
  FILTER (?director IN(dbpedia-ja:北野武, dbpedia-ja:ビートたけし)) .
}
ORDER BY ?screen_time
