PREFIX dbpedia-ja: <http://ja.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX prop-ja: <http://ja.dbpedia.org/property/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?director
 (COUNT(?film) AS ?count)
 (MAX(?screen_time) AS ?longest)
 (MIN(?screen_time) AS ?shortest)
 (SUM(?screen_time) AS ?sum)
 (ROUND(AVG(?screen_time)) AS ?average)
 (GROUP_CONCAT(?film_name; SEPARATOR = ", " ) AS ?films)
 (SAMPLE(?film_name) AS ?sample_film)
WHERE
{
  ?film dbpedia-owl:director ?director ;
    prop-ja:上映時間 ?screen_time ;
    rdfs:label ?film_name .
  FILTER (?director IN(dbpedia-ja:北野武, dbpedia-ja:ビートたけし)) .
}
GROUP BY ?director
