PREFIX dbpedia-ja: <http://ja.dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?work
WHERE
{
 ?work dbpedia-owl:director | dbpedia-owl:starring dbpedia-ja:ビートたけし . 
}
