PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?film
WHERE
{
 ?takeshi rdfs:label "ビートたけし"@ja .
 ?takeshi ^dbpedia-owl:director ?film .
}