PREFIX : <http://sparqlbook.jp/book/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
  ?s :nick_name_count ?count .
}
WHERE {
  SELECT ?s (COUNT(?nick_name) AS ?count)
  WHERE {
    ?s foaf:nick ?nick_name .
  }
}
